config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index' #dashboard
    resources :admins
    resources :subjects
    resources :questions
  end

  root to: 'site/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class AdminsController < AdminsBackofficeController
    before_action :verify_password, only: [:update, :create]
    before_action :set_admin, only: %i[edit update destroy]

    def index
      @admins = Admin.all.page(params[:page]).per(5)
    end

    def new
      @admin = Admin.new
    end

    def create
      @admin = Admin.new(params_admin)
      if @admin.save
        redirect_to admins_backoffice_admins_path, notice: 'Administrador cadastrado com sucesso!'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @admin.update(params_admin)
        redirect_to admins_backoffice_admins_path, notice: 'Administrador atualizado com sucesso!'
      else
        render :edit
      end
    end

    def destroy
      if @admin.destroy
        redirect_to admins_backoffice_admins_path, notice: 'Administrador excluido com sucesso!'
      else
        render :index
      end
    end

    private

    def params_admin
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def verify_password
      if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
        params[:admin].extract!(:password, :password_confirmation)
      end
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:edit, :new]

  def index
    @questions = Question.all.order(:description).page(params[:page]).includes([:subject])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso !"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description, :subject_id,
      answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
# frozen_string_literal: true

module AdminsBackoffice
  class SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: %i[edit update destroy]

    def index
      @subjects = Subject.all.page(params[:page]).per(5)
    end

    def new
      @subject = Subject.new
    end

    def create
      @subject = Subject.new(params_subject)
      if @subject.save
        redirect_to admins_backoffice_subjects_path, notice: 'Assunto cadastrado com sucesso!'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: 'Assunto atualizado com sucesso!'
      else
        render :edit
      end
    end

    def destroy
      if @subject.destroy
        redirect_to admins_backoffice_subjects_path, notice: 'Assunto excluido com sucesso!'
      else
        render :index
      end
    end

    private

    def params_subject
      params.require(:subject).permit(:description)
    end

    def set_subject
      @subject = Subject.find(params[:id])
    end
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object =  nil, method = nil)
    if object && method
      object.human_attribute_name(method)
    else
      "Informe os parâmetros corretamente !"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/_form.html.erb
<div class="container-fluid">
  <div class="card-body">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold "><%= action_message %></h3>
      </div>

      <% if @admin.errors.any? %>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
          <ul>
            <% @admin.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-6">
        <%= form_with(model: [ :admins_backoffice, @admin ],local: true) do |form| %>

          <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, class:"form-control", placeholder:"Digite Email" %>
          </div>
          <div class="form-group">
            <%= form.label :password %>
            <%= form.password_field :password, class:"form-control", placeholder:"Digite a senha" %>
          </div>
          <div class="form-group">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Cnfirme a senha" %>>
          </div>

          <button type="submit" class="btn btn-success">Salvar</button>
        <% end %>
      </div>
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-12 -->
</div>

app/views/admins_backoffice/admins/edit.html.erb
<%= render partial: 'admins_backoffice/admins/form', locals: {action_message: 'Editando'}  %>

app/views/admins_backoffice/admins/index.html.erb
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold "><%= t('messages.listing', model: @admins.model_name.human(count: 2)) %></h3>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th><%= translate_attribute(@admins, :email) %>></th>
              <th>
                <%= link_to new_admins_backoffice_admin_path, class:"btn btn-success btn-circle btn-sm" do %>
                  <i class="fa fa-plus"></i>
                <% end %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.id %></td>
              <td><%= admin.email %></td>
              <td style="width: 100px">
                <%= link_to edit_admins_backoffice_admin_path(admin), class:"btn btn-warning btn-circle btn-sm" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to admins_backoffice_admin_path(admin),method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: admin.email.truncate(15) ) } do %>
                  <i class="fa fa-remove"></i>
                <%end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="pagination justify-content-center">
        <%= paginate @admins %>
      </div>
    </div>
  </div>
</div>

app/views/admins_backoffice/admins/new.html.erb
<%= render partial: 'admins_backoffice/admins/form', locals: {action_message: 'Criando'}  %>

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested_fields">
  <%= f.label :description %></br>
  <%= f.text_field :description %>
  <%= f.check_box :correct %>Correta ?

  <%= link_to_remove_association('Remover', f) %>
</div>

app/views/admins_backoffice/questions/_form.html.erb
<div class="container-fluid">
  <div class="card-body">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold "><%= action_message %></h3>
      </div>

      <% if @question.errors.any? %>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
          <ul>
            <% @question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-6">
        <%= form_with(model: [ :admins_backoffice, @question ],local: true) do |form| %>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class:"form-control", placeholder:"Pergunta" %>
          </div>

          <div class="form-group">
            <%= form.label :subject_id %>
            <%= form.collection_select(:subject_id, @subjects, :id, :description, {}, {class:"form-control"} ) %>
          </div>

          <div id='answers'>
            <%= form.fields_for :answers do |answer| %>
              <%= render partial: "answer_fields", locals: { f: answer}  %>
            <% end %>

            <%= link_to_add_association '[Adicionar Resposta]', form, :answers  %>
          </div>

          <button type="submit" class="btn btn-success">Salvar</button>
        <% end %>
      </div>
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-12 -->
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/form', locals: {action_message: 'Editando'}  %>

app/views/admins_backoffice/questions/index.html.erb
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold "><%= t('messages.listing', model: @questions.model_name.human(count: 2)) %></h3>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th><%= translate_attribute(@questions, :description)%></th>
              <th><%= translate_attribute(@questions, :subject)%></th>
              <th>
                <%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle btn-sm" do %>
                  <i class="fa fa-plus"></i>
                <% end %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @questions.each do |question| %>
            <tr>
              <td><%= question.id %></td>
              <td><%= question.description %></td>
              <td><%= question.subject.description %></td>
              <td style="width: 100px">
                <%= link_to edit_admins_backoffice_question_path(question), class:"btn btn-warning btn-circle btn-sm" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to admins_backoffice_question_path(question),method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: question.description.truncate(15) ) } do %>
                  <i class="fa fa-remove"></i>
                <%end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="pagination justify-content-center">
        <%= paginate @questions %>
      </div>
    </div>
  </div>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/form', locals: {action_message: 'Criando'}  %>

app/views/admins_backoffice/subjects/_form.html.erb
<div class="container-fluid">
  <div class="card-body">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold "><%= action_message %></h3>
      </div>

      <% if @subject.errors.any? %>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
          <ul>
            <% @subject.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-6">
        <%= form_with(model: [ :admins_backoffice, @subject ],local: true) do |form| %>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_field :description, class:"form-control", placeholder:"Digite Assunto" %>
          </div>

          <button type="submit" class="btn btn-success">Salvar</button>
        <% end %>
      </div>
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-12 -->
</div>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/form', locals: {action_message: 'Editando'}  %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold "><%= t('messages.listing', model: @subjects.model_name.human(count: 2)) %></h3>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th><%= translate_attribute(@subjects, :description)%></th>
              <th>
                <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle btn-sm" do %>
                  <i class="fa fa-plus"></i>
                <% end %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @subjects.each do |subject| %>
            <tr>
              <td><%= subject.id %></td>
              <td><%= subject.description %></td>
              <td style="width: 100px">
                <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-warning btn-circle btn-sm" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to admins_backoffice_subject_path(subject),method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: subject.description.truncate(15) ) } do %>
                  <i class="fa fa-remove"></i>
                <%end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="pagination justify-content-center">
        <%= paginate @subjects %>
      </div>
    </div>
  </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/form', locals: {action_message: 'Criando'}  %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn btn-warning'  %>

app/views/site/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Seja Bem Vindo</h1>
  <p class="lead">Escolha uma opçao abaixo</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Admin', admins_backoffice_welcome_index_path, class: "btn btn-info" %>
    <%= link_to 'Usuário', users_backoffice_welcome_index_path, class: "btn btn-success" %>
  </p>
</div>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>